spring:
  datasource:
    #    驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://89.47.166.199/blog?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://89.47.166.199:3306/blog?useSSL=true&useUnicode=false
    password: MYMW2eFGLayH43D6
    username: blog
#控制台打印sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_
